# Program:	Webklient, IPK projekt 1
# Autor: 	Adam Ormandy

all: webclient

webclient: webclient.cpp
	g++ webclient.cpp -o webclient -std=gnu++11 -Wl,-rpath=/usr/local/lib/gcc49/


.PHONY: clean
clean:
	rm -f webclient

